// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// rstrauss_bbox_cpp
NumericMatrix rstrauss_bbox_cpp(int n, double xmin, double xmax, double ymin, double ymax, double r, double gamma, int sweeps, int burnin, int thin);
RcppExport SEXP _spesim_rstrauss_bbox_cpp(SEXP nSEXP, SEXP xminSEXP, SEXP xmaxSEXP, SEXP yminSEXP, SEXP ymaxSEXP, SEXP rSEXP, SEXP gammaSEXP, SEXP sweepsSEXP, SEXP burninSEXP, SEXP thinSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< int >::type n(nSEXP);
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< double >::type ymin(yminSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< double >::type r(rSEXP);
    Rcpp::traits::input_parameter< double >::type gamma(gammaSEXP);
    Rcpp::traits::input_parameter< int >::type sweeps(sweepsSEXP);
    Rcpp::traits::input_parameter< int >::type burnin(burninSEXP);
    Rcpp::traits::input_parameter< int >::type thin(thinSEXP);
    rcpp_result_gen = Rcpp::wrap(rstrauss_bbox_cpp(n, xmin, xmax, ymin, ymax, r, gamma, sweeps, burnin, thin));
    return rcpp_result_gen;
END_RCPP
}
// rthomas_bbox_cpp
NumericMatrix rthomas_bbox_cpp(double kappa, double mu, double sigma, double xmin, double ymin, double xmax, double ymax, int max_points);
RcppExport SEXP _spesim_rthomas_bbox_cpp(SEXP kappaSEXP, SEXP muSEXP, SEXP sigmaSEXP, SEXP xminSEXP, SEXP yminSEXP, SEXP xmaxSEXP, SEXP ymaxSEXP, SEXP max_pointsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< double >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< double >::type mu(muSEXP);
    Rcpp::traits::input_parameter< double >::type sigma(sigmaSEXP);
    Rcpp::traits::input_parameter< double >::type xmin(xminSEXP);
    Rcpp::traits::input_parameter< double >::type ymin(yminSEXP);
    Rcpp::traits::input_parameter< double >::type xmax(xmaxSEXP);
    Rcpp::traits::input_parameter< double >::type ymax(ymaxSEXP);
    Rcpp::traits::input_parameter< int >::type max_points(max_pointsSEXP);
    rcpp_result_gen = Rcpp::wrap(rthomas_bbox_cpp(kappa, mu, sigma, xmin, ymin, xmax, ymax, max_points));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_spesim_rstrauss_bbox_cpp", (DL_FUNC) &_spesim_rstrauss_bbox_cpp, 10},
    {"_spesim_rthomas_bbox_cpp", (DL_FUNC) &_spesim_rthomas_bbox_cpp, 8},
    {NULL, NULL, 0}
};

RcppExport void R_init_spesim(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
