# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast Strauss simulation on a bounding box (fixed-n Metropolis-Hastings)
NULL

rstrauss_bbox_cpp <- function(n, xmin, xmax, ymin, ymax, r, gamma, sweeps = 2000L, burnin = 200L, thin = 1L) {
    .Call(`_spesim_rstrauss_bbox_cpp`, n, xmin, xmax, ymin, ymax, r, gamma, sweeps, burnin, thin)
}

rthomas_bbox_cpp <- function(kappa, mu, sigma, xmin, ymin, xmax, ymax, max_points = -1L) {
    .Call(`_spesim_rthomas_bbox_cpp`, kappa, mu, sigma, xmin, ymin, xmax, ymax, max_points)
}

